# Generated by Django 3.2.9 on 2021-12-22 11:25

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerDate', models.DateField(unique_for_date='registerDate', verbose_name='Data Rejestracji')),
                ('year_copy', models.IntegerField(default=None, null=True)),
                ('month_copy', models.IntegerField(default=None, null=True)),
                ('reserved', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, '00:00 - 01:00'), (1, '01:00 - 02:00'), (2, '02:00 - 03:00'), (3, '03:00 - 04:00'), (4, '04:00 - 05:00'), (5, '05:00 - 06:00'), (6, '06:00 - 07:00'), (7, '07:00 - 08:00'), (8, '08:00 - 09:00'), (9, '09:00 - 10:00'), (10, '10:00 - 11:00'), (11, '11:00 - 12:00'), (12, '12:00 - 13:00'), (13, '13:00 - 14:00'), (14, '14:00 - 15:00'), (15, '15:00 - 16:00'), (16, '16:00 - 17:00'), (17, '17:00 - 18:00'), (18, '18:00 - 19:00'), (19, '19:00 - 20:00'), (20, '20:00 - 21:00'), (21, '21:00 - 22:00'), (22, '22:00 - 23:00'), (23, '23:00 - 00:00')], max_length=100, verbose_name='Zarezerwowane')),
                ('pending', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, '00:00 - 01:00'), (1, '01:00 - 02:00'), (2, '02:00 - 03:00'), (3, '03:00 - 04:00'), (4, '04:00 - 05:00'), (5, '05:00 - 06:00'), (6, '06:00 - 07:00'), (7, '07:00 - 08:00'), (8, '08:00 - 09:00'), (9, '09:00 - 10:00'), (10, '10:00 - 11:00'), (11, '11:00 - 12:00'), (12, '12:00 - 13:00'), (13, '13:00 - 14:00'), (14, '14:00 - 15:00'), (15, '15:00 - 16:00'), (16, '16:00 - 17:00'), (17, '17:00 - 18:00'), (18, '18:00 - 19:00'), (19, '19:00 - 20:00'), (20, '20:00 - 21:00'), (21, '21:00 - 22:00'), (22, '22:00 - 23:00'), (23, '23:00 - 00:00')], max_length=100, verbose_name='Oczekujące')),
            ],
            options={
                'verbose_name': 'rezerwacja',
                'verbose_name_plural': 'rezerwacje',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(choices=[(0, 'Parter'), (1, 'Pierwsze'), (2, 'Drugie')], default=0, verbose_name='Piętro')),
                ('room_number', models.PositiveIntegerField(verbose_name='Numer pokoju')),
                ('room_station', models.PositiveIntegerField(default=1, verbose_name='Numer stanowiska')),
                ('title', models.CharField(max_length=50, verbose_name='Nazwa pokoju')),
                ('description', models.TextField(verbose_name='Opis')),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('available', 'Dostępna'), ('disabled', 'Wyłączona')], default='disabled', max_length=10)),
            ],
            options={
                'verbose_name': 'Laboratorium',
                'verbose_name_plural': 'Laboratoria',
                'ordering': ('floor', 'room_number', 'room_station'),
                'unique_together': {('floor', 'room_number', 'room_station')},
            },
        ),
    ]
