# Generated by Django 3.2.9 on 2022-01-03 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Laboratoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationentry',
            name='res_name_0',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn0', to=settings.AUTH_USER_MODEL, verbose_name='00:00 - 01:00'),
        ),
        migrations.AddField(
            model_name='registrationentry',
            name='res_name_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn1', to=settings.AUTH_USER_MODEL, verbose_name='01:00 - 02:00'),
        ),
        migrations.AddField(
            model_name='registrationentry',
            name='res_name_10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn10', to=settings.AUTH_USER_MODEL, verbose_name='10:00 - 11:00'),
        ),
        migrations.AddField(
            model_name='registrationentry',
            name='res_name_11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn11', to=settings.AUTH_USER_MODEL, verbose_name='11:00 - 12:00'),
        ),
        migrations.AddField(
            model_name='registrationentry',
            name='res_name_12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn12', to=settings.AUTH_USER_MODEL, verbose_name='12:00 - 13:00'),
        ),
        migrations.AddField(
            model_name='registrationentry',
            name='res_name_13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn13', to=settings.AUTH_USER_MODEL, verbose_name='13:00 - 14:00'),
        ),
        migrations.AddField(
            model_name='registrationentry',
            name='res_name_14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn14', to=settings.AUTH_USER_MODEL, verbose_name='14:00 - 15:00'),
        ),
        migrations.AddField(
            model_name='registrationentry',
            name='res_name_15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn15', to=settings.AUTH_USER_MODEL, verbose_name='15:00 - 16:00'),
        ),
        migrations.AddField(
            model_name='registrationentry',
            name='res_name_16',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn16', to=settings.AUTH_USER_MODEL, verbose_name='16:00 - 17:00'),
        ),
        migrations.AddField(
            model_name='registrationentry',
            name='res_name_17',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn17', to=settings.AUTH_USER_MODEL, verbose_name='17:00 - 18:00'),
        ),
        migrations.AddField(
            model_name='registrationentry',
            name='res_name_18',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn18', to=settings.AUTH_USER_MODEL, verbose_name='18:00 - 19:00'),
        ),
        migrations.AddField(
            model_name='registrationentry',
            name='res_name_19',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn19', to=settings.AUTH_USER_MODEL, verbose_name='19:00 - 20:00'),
        ),
        migrations.AddField(
            model_name='registrationentry',
            name='res_name_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn2', to=settings.AUTH_USER_MODEL, verbose_name='02:00 - 03:00'),
        ),
        migrations.AddField(
            model_name='registrationentry',
            name='res_name_20',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn20', to=settings.AUTH_USER_MODEL, verbose_name='20:00 - 21:00'),
        ),
        migrations.AddField(
            model_name='registrationentry',
            name='res_name_21',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn21', to=settings.AUTH_USER_MODEL, verbose_name='21:00 - 22:00'),
        ),
        migrations.AddField(
            model_name='registrationentry',
            name='res_name_22',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn22', to=settings.AUTH_USER_MODEL, verbose_name='22:00 - 23:00'),
        ),
        migrations.AddField(
            model_name='registrationentry',
            name='res_name_23',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn23', to=settings.AUTH_USER_MODEL, verbose_name='23:00 - 00:00'),
        ),
        migrations.AddField(
            model_name='registrationentry',
            name='res_name_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn3', to=settings.AUTH_USER_MODEL, verbose_name='03:00 - 04:00'),
        ),
        migrations.AddField(
            model_name='registrationentry',
            name='res_name_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn4', to=settings.AUTH_USER_MODEL, verbose_name='04:00 - 05:00'),
        ),
        migrations.AddField(
            model_name='registrationentry',
            name='res_name_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn5', to=settings.AUTH_USER_MODEL, verbose_name='05:00 - 06:00'),
        ),
        migrations.AddField(
            model_name='registrationentry',
            name='res_name_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn6', to=settings.AUTH_USER_MODEL, verbose_name='06:00 - 07:00'),
        ),
        migrations.AddField(
            model_name='registrationentry',
            name='res_name_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn7', to=settings.AUTH_USER_MODEL, verbose_name='07:00 - 08:00'),
        ),
        migrations.AddField(
            model_name='registrationentry',
            name='res_name_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn8', to=settings.AUTH_USER_MODEL, verbose_name='08:00 - 09:00'),
        ),
        migrations.AddField(
            model_name='registrationentry',
            name='res_name_9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn9', to=settings.AUTH_USER_MODEL, verbose_name='09:00 - 10:00'),
        ),
        migrations.AddField(
            model_name='registrationentry',
            name='roomConnector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Laboratoria.room', verbose_name='Dotyczy'),
        ),
        migrations.AlterField(
            model_name='registrationentry',
            name='registerDate',
            field=models.DateField(verbose_name='Data Rejestracji'),
        ),
        migrations.AlterUniqueTogether(
            name='registrationentry',
            unique_together={('registerDate', 'roomConnector')},
        ),
    ]
